### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by DearTanker** [alexzhangs/shadowsocks-manager#1]
```
[root@do-1v-2g-2t-sfo2-01 shadowsocks-manager]# pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting backports.weakref (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/88/ec/f598b633c3d5ffe267aaada57d961c94fdfa183c5c3ebda2b6d151943db6/backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting celery==4.3.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/5c/a1/a3dd9d8bfa09156ec2cba37f90accf35c0f4ecc3980d96cb4fb99e56504b/celery-4.3.0-py2.py3-none-any.whl
Collecting Django==1.11.20 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/8e/1f/20bbc601c442d02cc8d9b25a399a18ef573077e3350acdf5da3743ff7da1/Django-1.11.20-py2.py3-none-any.whl
Collecting django-cache-lock==0.2.1 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/b7/e4/baa986fb268430d313d4f780c906ebfe2a6eaac30236955edb993833445d/django_cache_lock-0.2.1-py2.py3-none-any.whl
Collecting django-celery-beat==1.5.0 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/88/13/2dbab42ea826efab897d8638304d499078e0093e73c9b5fa19259e48ea94/django_celery_beat-1.5.0-py2.py3-none-any.whl
Collecting django-celery-results==1.1.1 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/1d/3f/a82aa9fb1f2e35a72a710134a7bf9d9b1dc45dea9f6c2c16d06bb6363554/django_celery_results-1.1.1-py2.py3-none-any.whl
Collecting django-enumfield==1.5 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/ff/47/7d4c29c841e32e047dc22526f17259fd280ec1dbb5f609c7d29155f1ffe9/django-enumfield-1.5.tar.gz
Collecting django-import-export==1.2.0 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/62/7a/ddd9aef718243504e7715bda9bb5a100cfc353be37dc819d9914a7073cba/django_import_export-1.2.0-py2.py3-none-any.whl
Collecting djangorestframework==3.9.2 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/cc/6d/5f225f18d7978d8753c1861368efc62470947003c7f9f9a5cc425fc0689b/djangorestframework-3.9.2-py2.py3-none-any.whl
Collecting python-memcached==1.59 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/f5/90/19d3908048f70c120ec66a39e61b92c253e834e6e895cd104ce5e46cbe53/python_memcached-1.59-py2.py3-none-any.whl
Collecting pytz==2019.1 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting requests==2.22.0 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting vine>=1.3.0 (from celery==4.3.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7f/60/82c03047396126c8331ceb64da1dc52d4f1317209f32e8fe286d0c07365a/vine-1.3.0-py2.py3-none-any.whl
Collecting billiard<4.0,>=3.6.0 (from celery==4.3.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/68/1d/2aea8fbb0b1e1260a8a2e77352de2983d36d7ac01207cf14c2b9c6cc860e/billiard-3.6.1.0.tar.gz
Collecting kombu<5.0,>=4.4.0 (from celery==4.3.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bb/22/58104fd214fb32008f2f4d64a1918c81e353f23e7beee9605674f9ecd6b2/kombu-4.6.4-py2.py3-none-any.whl
Requirement already satisfied: six>=1.0.0 in /usr/lib/python2.7/site-packages (from django-cache-lock==0.2.1->-r requirements.txt (line 4)) (1.9.0)
Collecting django-timezone-field>=2.0 (from django-celery-beat==1.5.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/1a/c0/6aa03df6a901123b9eeb7fbc8ea64f9e8f9f4a1a10ab91313ac2b1d46c0e/django_timezone_field-3.0-py2.py3-none-any.whl
Collecting python-crontab>=2.3.4 (from django-celery-beat==1.5.0->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/01/3f/e81716ba2592e7006c174251f70486b7e1d06abea80fe0c25a07d6527f5b/python-crontab-2.3.9.tar.gz
Collecting tablib (from django-import-export==1.2.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/77/bf/c58a0aaf9e94c002955ae64f1bfd044dc5f34b3e9b278de152402560d060/tablib-0.13.0.tar.gz
Collecting diff-match-patch (from django-import-export==1.2.0->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/f0/2a/5ba07def0e9107d935aba62cf632afbd0f7c723a98af47ccbcab753d2452/diff-match-patch-20181111.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zj0lvn/diff-match-patch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zj0lvn/diff-match-patch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-zj0lvn/diff-match-patch/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zj0lvn/diff-match-patch/setup.py", line 37, in <module>
        install_requires=[],
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (setuptools 0.9.8 (/usr/lib/python2.7/site-packages), Requirement.parse('setuptools>=38.6.0'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by DearTanker** [comment]
USE `pip install -U setuptools` to solve the problem, but get a new one :

```
[root@do-1v-2g-2t-sfo2-01 shadowsocks-manager]# pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: backports.weakref in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.0.post1)
Requirement already satisfied: celery==4.3.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (4.3.0)
Requirement already satisfied: Django==1.11.20 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.11.20)
Requirement already satisfied: django-cache-lock==0.2.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.2.1)
Requirement already satisfied: django-celery-beat==1.5.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: django-celery-results==1.1.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: django-enumfield==1.5 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (1.5)
Requirement already satisfied: django-import-export==1.2.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: djangorestframework==3.9.2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9)) (3.9.2)
Requirement already satisfied: python-memcached==1.59 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 10)) (1.59)
Requirement already satisfied: pytz==2019.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 11)) (2019.1)
Collecting requests==2.22.0 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Requirement already satisfied: vine>=1.3.0 in /usr/lib/python2.7/site-packages (from celery==4.3.0->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: billiard<4.0,>=3.6.0 in /usr/lib/python2.7/site-packages (from celery==4.3.0->-r requirements.txt (line 2)) (3.6.1.0)
Requirement already satisfied: kombu<5.0,>=4.4.0 in /usr/lib/python2.7/site-packages (from celery==4.3.0->-r requirements.txt (line 2)) (4.6.4)
Requirement already satisfied: six>=1.0.0 in /usr/lib/python2.7/site-packages (from django-cache-lock==0.2.1->-r requirements.txt (line 4)) (1.9.0)
Requirement already satisfied: django-timezone-field>=2.0 in /usr/lib/python2.7/site-packages (from django-celery-beat==1.5.0->-r requirements.txt (line 5)) (3.0)
Requirement already satisfied: python-crontab>=2.3.4 in /usr/lib/python2.7/site-packages (from django-celery-beat==1.5.0->-r requirements.txt (line 5)) (2.3.9)
Requirement already satisfied: tablib in /usr/lib/python2.7/site-packages (from django-import-export==1.2.0->-r requirements.txt (line 8)) (0.13.0)
Requirement already satisfied: diff-match-patch in /usr/lib/python2.7/site-packages (from django-import-export==1.2.0->-r requirements.txt (line 8)) (20181111)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests==2.22.0->-r requirements.txt (line 12)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python2.7/site-packages (from requests==2.22.0->-r requirements.txt (line 12)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests==2.22.0->-r requirements.txt (line 12)) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests==2.22.0->-r requirements.txt (line 12)) (2019.9.11)
Requirement already satisfied: amqp<3.0,>=2.5.1 in /usr/lib/python2.7/site-packages (from kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (2.5.1)
Requirement already satisfied: importlib-metadata>=0.18 in /usr/lib/python2.7/site-packages (from kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (0.23)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from python-crontab>=2.3.4->django-celery-beat==1.5.0->-r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: odfpy in /usr/lib/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: openpyxl>=2.4.0 in /usr/lib/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (2.6.4)
Requirement already satisfied: backports.csv in /usr/lib/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.0.7)
Requirement already satisfied: xlrd in /usr/lib/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.2.0)
Requirement already satisfied: xlwt in /usr/lib/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.3.0)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (3.10)
Requirement already satisfied: configparser>=3.5; python_version < "3" in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (4.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: contextlib2; python_version < "3" in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (0.6.0)
Requirement already satisfied: pathlib2; python_version == "3.4.*" or python_version < "3" in /usr/lib/python2.7/site-packages (from importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (2.3.4)
Requirement already satisfied: defusedxml in /usr/lib/python2.7/site-packages (from odfpy->tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (0.6.0)
Requirement already satisfied: jdcal in /usr/lib/python2.7/site-packages (from openpyxl>=2.4.0->tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.4.1)
Requirement already satisfied: et_xmlfile in /usr/lib/python2.7/site-packages (from openpyxl>=2.4.0->tablib->django-import-export==1.2.0->-r requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: more-itertools in /usr/lib/python2.7/site-packages (from zipp>=0.5->importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (5.0.0)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/lib64/python2.7/site-packages (from pathlib2; python_version == "3.4.*" or python_version < "3"->importlib-metadata>=0.18->kombu<5.0,>=4.4.0->celery==4.3.0->-r requirements.txt (line 2)) (1.10.0)
Installing collected packages: requests
  Found existing installation: requests 2.6.0
ERROR: Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by alexzhangs** [comment]
It's better to install the project within a virtualenv, avoid to impact existing packages.
I'll document more detail about my testing environment.
